---
resources:

  # Where we will push the binaries
#  - name: bucket
#    type: s3
#    source:
#      bucket: radicle-releases
#      regexp: radicle-github-actions-adapter/(.*)
#      access_key_id: ((access_key_id))
#      secret_access_key: ((secret_access_key))
#      endpoint: minio-api.radicle.gr

jobs:
  -
  # test-source for errors
  - name: test-source
    plan:
      - task: test
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: golang
              tag: 1.21.0
          run:
            path: sh
            args:
              - -c
              - |
                git clone ((repo_clone_url)) github-actions-adapter
                cd github-actions-adapter
                git fetch --all
                git checkout ((commit_hash))
                ls -al
                make build
                make tidy
                make test

      # release-binaries if tests pass and new version is released
      - task: release-binaries
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: golang
              tag: 1.21.0
          outputs:
            - name: binaries
          run:
            path: sh
            args:
              - -c
              - |
                ls -al
                COMMIT_HASH=$(git rev-parse HEAD)
                VERSION="test"
                echo Releasing version: $VERSION
                env GOOS=linux GOARCH=amd64 go build -ldflags "-X 'radicle-github-actions-adapter/pkg/version.Version=$VERSION' -X 'radicle-github-actions-adapter/pkg/version.BuildTime=$(date)'" -o=/tmp/binaries/radicle-github-actions-adapter-linux-amd64-$VERSION ./cmd/github-actions-adapter
                env GOOS=linux GOARCH=arm64 go build -ldflags "-X 'radicle-github-actions-adapter/pkg/version.Version=$VERSION' -X 'radicle-github-actions-adapter/pkg/version.BuildTime=$(date)'" -o=/tmp/binaries/radicle-github-actions-adapter-linux-arm64-$VERSION ./cmd/github-actions-adapter
                env GOOS=darwin GOARCH=amd64 go build -ldflags "-X 'radicle-github-actions-adapter/pkg/version.Version=$VERSION' -X 'radicle-github-actions-adapter/pkg/version.BuildTime=$(date)'" -o=/tmp/binaries/radicle-github-actions-adapter-darwin-amd64-$VERSION ./cmd/github-actions-adapter
                env GOOS=darwin GOARCH=arm64 go build -ldflags "-X 'radicle-github-actions-adapter/pkg/version.Version=$VERSION' -X 'radicle-github-actions-adapter/pkg/version.BuildTime=$(date)'" -o=/tmp/binaries/radicle-github-actions-adapter-darwin-arm64-$VERSION ./cmd/github-actions-adapter

      # push images
#      - put: bucket
#        params:
#          file: binaries/radicle-github-actions-adapter-linux-amd64*
#          acl: public-read
#      - put: bucket
#        params:
#          file: binaries/radicle-github-actions-adapter-linux-arm64*
#          acl: public-read
#      - put: bucket
#        params:
#          file: binaries/radicle-github-actions-adapter-darwin-amd64*
#          acl: public-read
#      - put: bucket
#        params:
#          file: binaries/radicle-github-actions-adapter-darwin-arm64*
#          acl: public-read
