resources:
# The repo resource
- name: github-actions-adapter
  type: git
  icon: git
  source:
    uri: https://seed.radicle.gr/zyMFFgrGTswVFj1X9uJrVwEV8EWu.git
    branch: main
    git_config:
      - name: safe.directory
        value: /tmp/build/get

# Where we will push the binaries
- name: bucket
  type: s3
  source:
    bucket: radicle-releases
    regexp: radicle-github-actions-adapter/(.*)
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    endpoint: minio-api.radicle.gr

jobs:
- name: release-pipeline
  plan:
  - check: github-actions-adapter
    trigger: true

  # test source
  - task: test
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: golang
          tag: 1.21.0
      inputs:
        - name: github-actions-adapter
      run:
        path: sh
        args:
          - -c
          - |
            cd github-actions-adapter
            make tidy
            make test
