resources:
# The repo resource
- name: github-actions-adapter
  type: git
  icon: git
  source:
    uri: https://seed.radicle.gr/zyMFFgrGTswVFj1X9uJrVwEV8EWu.git
    branch: main
    paths:
      - README.md
    git_config:
      - name: safe.directory
        value: /tmp/build/get

# Where we will push the binaries
- name: bucket
  type: s3
  source:
    bucket: radicle-releases
    regexp: radicle-github-actions-adapter/(.*)
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    endpoint: minio-api.radicle.gr

jobs:
- name: release-pipeline
  plan:
  - check: github-actions-adapter
    trigger: true

  # test source
  - task: test
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: golang
          tag: 1.21.0
      inputs:
        - name: github-actions-adapter
      run:
        path: sh
        args:
          - -c
          - |
            cd github-actions-adapter
            make tidy
            make test

  # build images
  - task: build-binaries
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: golang
          tag: 1.21.0

      inputs:
      - name: github-actions-adapter
      outputs:
      - name: binaries
      run:
        path: sh
        args:
        - -c
        - |
          cd github-actions-adapter
          COMMIT_HASH=$(git rev-parse HEAD)
          VERSION=$(head -n 1 CHANGELOG.md)
          echo Building version: $VERSION
          echo $(date)
          echo now is $(date) - $COMMIT_HASH
          echo radicle-github-actions-adapter-linux-amd64-$VERSION-$COMMIT_HASH

  # push images
  - put: bucket
    params:
      file: binaries/radicle-github-actions-adapter-linux-amd64*
      acl: public-read
  - put: bucket
    params:
      file: binaries/radicle-github-actions-adapter-linux-arm64*
      acl: public-read
  - put: bucket
    params:
      file: binaries/radicle-github-actions-adapter-darwin-amd64*
      acl: public-read
  - put: bucket
    params:
      file: binaries/radicle-github-actions-adapter-darwin-arm64*
      acl: public-read
